version: '3.8'

services:
  # 開発環境
  app-dev:
    build:
      context: ../frontend
      dockerfile: ../infrastructure/docker/Dockerfile
      target: deps
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
      - ../frontend/next.config.mjs:/app/next.config.mjs
      - ../frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ../frontend/tsconfig.json:/app/tsconfig.json
      - ../frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ../frontend/components.json:/app/components.json
    environment:
      - NODE_ENV=development
    command: pnpm dev
    profiles:
      - dev

  # 本番環境
  app-prod:
    build:
      context: ../frontend
      dockerfile: ../infrastructure/docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    profiles:
      - prod

  # Nginx（本番環境用）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app-prod
    profiles:
      - prod 